# Topic2 - Randomness

## Exercise 1

In [1]:
# For generating numbers.
import numpy as np

In [4]:
# Flip a fair coin.
np.random.binomial(1, 0.5)

0

In [5]:
# Flip a fair coin 100 times.
np.random.binomial(1, 0.5, 100)

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [6]:
# Flip a fair coin 100 times, giving only the total number of heads.
np.random.binomial(100, 0.5)

54

In [8]:
# Keep flipping coins until we get three examples of getting five heads in ten coin tosses.

# Number of examples.
N = 3

# Keep track of number of arrays generated.
total_no = 0

# Keep trying until we get three examples.
while N > 0:
    # Add 1 to total.
    total_no = total_no + 1
    # Toss 10 coins.
    tosses = np.random.binomial(1, 0.5, 10)
    # Check if we got five heads.
    if tosses.sum() == 5:
        # If we got 5 heads, print the list of heads/tails.
        print(tosses)
        # Reduce the number of examples left to find by 1.
        N = N - 1

print(f'Total generated: {total_no}')

[1 0 0 1 1 1 1 0 0 0]
[0 1 1 1 0 1 0 0 0 1]
[1 0 0 1 1 0 0 1 0 1]
Total generated: 10


##Topic Question -Exercise 1

It is somewhat interesting that (5 * 4 * 3 * 2 * 1) perfectly divides (10 * 9 * 8 * 7 * 6) - there's no remainder.

If we only wanted exactly four heads as opposed to five, the equivalent calculation would be (10 * 9 * 8 * 7) / (4 * 3 * 2 * 1).

Does that evenly divide too? What is the formula in general?

Does it always come out as a positive whole number?

In [ ]:
(10 * 9 * 8 * 7) // (4 * 3 * 2 * 1)

From applying the above formula we can see that the it does evenly divide on one run when using "//" for real whole numbers.

In [ ]:
WholeNumber = (10 * 9 * 8 * 7) // (4 * 3 * 2 * 1)
print(WholeNumber)

In [ ]:
i = 1
while i <= 100:
    print("Division is a positive whole number")
    i += 1